spring:
  application:
    name: authservice

  datasource:
#    url: jdbc:mysql://localhost:3306/auth_db
#    username: root
#    password: ${SPRING_DATASOURCE_PASSWORD}
    url: jdbc:mysql://all-ativityplanner-db.chi8ecww0ayl.ap-south-1.rds.amazonaws.com:3306/auth_db
    username: admin
    password: ${SPRING_DATASOURCE_PASSWORD}
    jpa:
      hibernate:
        ddl-auto: validate
      show-sql: false

server:
  port: 8080
jwt:
  secret: ${APP_JWT_SECRET}
